### ISSUE TITLE
Build issue with vue-cli & webpack

### ISSUE THREAD

**Issue by zub0r** [wangzhiguoengineer/vuex-facing-decorator#1]
Hi, I'm trying to use this package with an older vue app, which I'm trying to migrate from vue 2 to vue 3, while sticking to vue-cli + webpack due to legacy code.

For some reason, the vue-cli can't process the js files of this package which are esm modules:

```
 ERROR  Failed to compile with 1 error
 error  in ./node_modules/vuex-facing-decorator/dist/esm/index.js

Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> import { BindProperty } from './const';
```
My understanding is that vue-cli should distinguish esm module even in the js file, but it is not the case.
Any suggestions would be highly appreciated.
Thanks!

**Comment by wangzhiguoengineer** [comment]
The package. json version v1.0.3 has removed type=commonjs. You can try this version.
Here are my suggestions:
1. Using vuex-facing-decorator@1.0.3 Version;
2. Using typescript@5 Version;
3. Check if the `type` configuration item of your project's `package.json` is correct;
4. Check if the `module` configuration item for `tsconfig.json` in your project is correct.

**Comment by zub0r** [comment]
Thanks a lot! 1.0.3 builds without problems
