### ISSUE TITLE
namespaced vs. namespace

### ISSUE THREAD

**Issue by gionkunz** [wangzhiguoengineer/vuex-facing-decorator#2]
Hi there

Thanks for providing this library. It helps a lot in the migration process from Vue2 class-based to Vue3.

I've noticed there's a settle difference in your library compared to vuex-class:

Vuex-class:
```
@Getter('activeSet', { namespace: customizationSetNamespace })
```

vuex-facing-decorator:
```
@Getter('activeSet', { namespaced: customizationSetNamespace })
```

Was this intentional? It would be great if the API is 100% equivalent to vuex-class for people who migrate to it.

**Comment by wangzhiguoengineer** [comment]
Thank you for feedback. I have corrected namespaced to namespace in version 1.1.0. You can try this version `vuex-facing-decorator@1.1.0`
